server:
  port: 8200


eureka:
  client:
    service-url:
      defaultZone: http://song:song@127.0.0.1:7000/eureka
#  instance:
#    prefer-ip-address: true

spring:
  application:
    name: websocket
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    service:
      name: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: '*'


