justauth:
  enabled: true
  type:
    WECHAT_OPEN:
      client-id: wxd853562a0548a7d0
      client-secret: 4a5d5615f93f24bdba2ba8534642dbb6
      redirect-uri: http://bugtracker.itsource.cn/wx/callback

spring:
  application:
    name: goods
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root

  redis:
    host: 192.168.137.37

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7000/eureka
server:
  port: 80