spring:
  application:
    name: gateway
  profiles:
    active: zuul
  cloud:
    gateway:
      discovery:
        locator:
          #开启基于注册发现
          enabled: true
          #开启小写验证
          lower-case-service-id: true

      routes:
        - id: goods
          uri: lb://GOODS
          predicates:
          - Path=/brand/**
#          filtes:
#            - StripPrefix=1

        - id: user
          uri: lb://USER
          predicates:
          - Path=/user/**
#          filetes:
#            - StripPrefix=1

        - id: websocket
          uri: lb:ws://WEBSOCKET
          predicates:
          - Path=/websocket/service/**

        - id: websocketpage
          uri: lb://WEBSOCKET
          predicates:
          - Path=/websocket/templates/**


        - login:
          uri: lb://LOGIN
          predicates:
          - Path=/login/**
          - Path=/wx/callback/**
          - Path=/page/**
#          filetes:
#            - StripPrefix=1


eureka:
  client:
    service-url:
      defaultZone: http://song:song@localhost:7000/eureka

      #将Ip注册上去

  instance:
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}:${server.port}

server:
  port: 9000

ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间

management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.cloud.gateway: debug
