fdfs:
  thumb-image:
    height: 200
    width: 200
  so-timeout: 1500
  connect-timeout: 600
  tracker-list: 192.168.205.128:22122

#nginx访问地址，用来获取图片  url/M00/xxx/xxxx.jpg
nginx:
  url: Http://192.168.205.128:8080/

spring:
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB

# 可以直接配置视图解析地址
#  mvc:
#    view:
#      prefix: /WEB-INF/
#      suffix: .jsp
