server:
  port: 9000

spring:
  application:
    name: gateway
  profiles:
    active: zuul

  security:
    user:
      name: song
      password: song

eureka:
  client:
    service-url:
      defaultZone: http://song:song@localhost:7000/eureka

      #将Ip注册上去
  instance:
    prefer-ip-address: true
#    ip-address: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 7000  #请求处理的超时时间
  ConnectTimeout: 7000  #请求连接的超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms


---
spring:
  profiles: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'


      routes:
        - id: user  #这个id只是为了分组
          uri: lb://USER
          predicates:
            - Path=/user/**

        - id: goods
          uri: lb://GOODS
          predicates:
            - Path=/brand/**



      discovery:
        locator:
          lower-case-service-id: true
          enabled: true



---
#zuul:
#  routes:
#    goods:
#      path: /goods/**
#      serviceId: goods
spring:
  profiles: zuul



zuul:
  routes:
    goods:
      path: /goods/**
      serviceId: GOODS
      stripPrefix: true

    user:
      path: /user/**
      serviceId: USER
      stripPrefix: true

    websocket:
      path: /websocket/**
      serviceId: WEBSOCKET

    login:
      path: /login/**
      serviceId: LOGIN
      stripPrefix: false

    order:
      path: /order/**
      serviceId: ORDER
      stripPrefix: true


  #add-host-header: true
  sensitive-headers: '*'
  retryable: false

  #忽略路由
  ignored-services: '*'

#是否开启swagger
swagger:
  enable: true


