server:
  port: 9000

  servlet:
    session:
      cookie:
        name: CGSESSION

spring:
  application:
    name: gateway
#  profiles:
#    active: zuul

  security:
#    user:
#      name: song
#      password: song

security:
  basic:
    enabled: false
#--------------oauth2配置---------------

  oauth2:
    client:

      access-token-uri: http://localhost:9000/login/oauth/token
      user-authorization-uri: http://localhost:9000/login/oauth/authorize
      #client-id: client_1
    resource:
      user-info-uri:  http://localhost:9000/login/user
      prefer-token-info: false



eureka:
  client:
    service-url:
      defaultZone: http://song:song@localhost:7000/eureka

      #将Ip注册上去
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 7000  #请求处理的超时时间
  ConnectTimeout: 7000  #请求连接的超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000 # 熔断超时时长：10000ms




#通过3个横线区分不同的配置

zuul:
  routes:
    goods:
      path: /goods/**
      serviceId: GOODS
      stripPrefix: true

    user:
      path: /user/**
      serviceId: USER
      stripPrefix: true

    websocket:
      path: /websocket/**
      serviceId: WEBSOCKET

    login:
      path: /login/**
      serviceId: LOGIN
      stripPrefix: true

    order:
      path: /order/**
      serviceId: ORDER
      stripPrefix: true


  #add-host-header: true
  sensitive-headers:
  retryable: false

  #忽略路由
  ignored-services: '*'
  add-proxy-headers: true


#是否开启swagger
swagger:
  enable: true


