server:
  port: 9000

spring:
  application:
    name: gateway
  profiles:
    active: zuul

  security:
    user:
      name: song
      password: song

eureka:
  client:
    service-url:
      defaultZone: http://song:song@localhost:7000/eureka

      #将Ip注册上去
#  instance:
#    prefer-ip-address: true
#    ip-address: ${spring.cloud.client.ip-address}:${server.port}

ribbon:
  ReadTimeout: 7000  #请求处理的超时时间
  ConnectTimeout: 7000  #请求连接的超时时间

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

---
spring:
  profiles: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: '*'


      routes:
        - id: user  #这个id只是为了分组
          uri: lb://USER
          predicates:
            - Path=/user/**

        - id: goods
          uri: lb://GOODS
          predicates:
            - Path=/brand/**



      discovery:
        locator:
          lower-case-service-id: true
          enabled: true



---
#zuul:
#  routes:
#    goods:
#      path: /goods/**
#      serviceId: goods
spring:
  profiles: zuul

  redis:
    timeout: 5000
    host: localhost
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root




zuul:
  routes:
    goods:
      path: /brand/**
      serviceId: GOODS
      stripPrefix: false

    user:
      path: /user/**
      serviceId: USER
      stripPrefix: false

    websocket:
      path: /websocket/**
      serviceId: WEBSOCKET

    login:
      path: /login/**
      serviceId: LOGIN
      stripPrefix: false


    login2:
      path: /wx/callback/**
      serviceId: LOGIN

    login-static:
      path: /page/**
      serviceId: LOGIN
  #add-host-header: true
  sensitive-headers:


#是否开启swagger
swagger:
  enable: true


