server:
  port: 8400
spring:
  application:
    name: cache
  redis:
    jedis:
      pool:
        max-active: 100
    host: localhost
    port: 6379
    password:
    timeout: 5000

#  cache:
#    type: caffeine
#    caffeine:
#      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=15s