server:
  port: 8000

#整合第三方登录的框架
justauth:
  enabled: true
  type:
    WECHAT_OPEN:
      client-id: wxd853562a0548a7d0
      client-secret: 4a5d5615f93f24bdba2ba8534642dbb6
      redirect-uri: http://bugtracker.itsource.cn/wx/callback

spring:
  application:
    name: login
  datasource:
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root
  cloud:
    zookeeper:
      connectString: localhost:2181,localhost:2182
      enabled: true
      #拉取zookeeper上的配置文件信息，路径为：/configurations/changgou/${profile.active}/apps
      config:
        enabled: true
        root: /configurations/changgou/${profile.active}
        defaultContext: apps
        profileSeparator: ':'

  #jackson的配置（标准）：
  jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  default-property-inclusion: always
  deserialization.fail_on_unknown_properties: false
  locale: zh_CN
  serialization.write_dates_as_timestamps: false

  redis:
    host: localhost
  #对session统一管理
  session:
    store-type: redis

ribbon:
  ConnectTimeout: 7000
  ReadTimeout: 7000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10
  threadpool:
    default:
      coreSize: 80
      maxQueueSize: 300
      queueSizeRejectionThreshold: 30111


logging:
  level:
    com.song: debug

#  mvc:
#    #static-path-pattern: /static/**
#    view:
#      prefix: /static/
#      suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://song:song@127.0.0.1:7000/eureka
  instance:
    prefer-ip-address: true


#存放redis中的验证码前缀
redis:
  image:
    code: REDIS_IMAGE_CODE_

mybatis:
  type-aliases-package: com.song.entity
  mapper-locations: classpath:/mapper/*.xml


