server:
  port: 8700

eureka:
  client:
    service-url:
      defaultZone: http://song:song@127.0.0.1:7000/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: schedul

management:
  endpoints:
    web:
      exposure:
        include: '*'

