server:
  port: 8900
spring:
  application:
    name: coupon

  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/changgou?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: root


eureka:
  client:
    service-url:
      defaultZone: http://song:song@127.0.0.1:7000/eureka

  instance:
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.song.entity
  mapper-locations: classpath:/mapper/*.xml